### ISSUE TITLE
[Gridsome] ModuleBuildError: Module build failed

### ISSUE THREAD

**Issue by Tragio** [unematiii/css-loader-short-classnames#1]
Hello @unematiii 🙂 

First of all, really thank you for this work and contribution to the community!

I've tried this package and some other methods but nothing seems to work. I spend some hours around this but I was not able to find a solution.

I was trying to reduce the CSS class names as Bulma has long names. I'm sure it will reduce heavily the CSS file size. I'm using Gridsome and Buefy. 

Attached is a file with all the methods I've tried and the result and errors from them. You can also check it here [http://pastie.org/p/1wpSI1AMvK3T6MZ23tXsLB](http://pastie.org/p/1wpSI1AMvK3T6MZ23tXsLB).

I've sent this to another developer to see if it was working from his side but he faced the same problems.

Not sure if is Gridsome, Buefy, SASS fault or something else.

Really thank you and have a beautiful week 😄 

[debug.js.zip](https://github.com/unematiii/css-loader-short-classnames/files/5337030/debug.js.zip)

**Comment by unematiii** [comment]
Hey! Thanks for your feedback. Ill check this thoroughly somewhere this week. However, having quick peek on you pastie, you could try modify CSS loader part in methods 1 & 4:
```js
{
 loader: "css-loader",
  options: {
    modules: { 
      localIdentName: "[name]_[local]_[hash:base64:5]",
      ...(isProduction ? { getLocalIdent: getLocalIdentName() } : {}), 
    },
  },
},
`
and try building for production (do make sure the `isProduction` flag is actually true).

Unsure about whats going in 2 & 3, will check this and get back to you...

**Comment by unematiii** [comment]
I did some research and apparently Gridsome CLI generated projects seem to pull in `css-loader` version `2.1.1` (latest is `4.3.0`), and for this version options should be provided differently:

`gridsome.config.js`:

```js
const { getLocalIdentName } = require("css-loader-shorter-classnames");

const isProduction = process.env.NODE_ENV === "production";

module.exports = {
  // ... other config options
  css: {
    loaderOptions: {
      css: {
        localIdentName: "[local]-[hash:base64:8]",
        ...(isProduction ? { getLocalIdent: getLocalIdentName() } : {}),
      },
    },
  },
};
```

Attaching [sample project](https://github.com/unematiii/css-loader-short-classnames/files/5339666/gridsome-test.zip) with working configuration.

**Comment by Tragio** [comment]
Hello @unematiii!! You're amazing, really thank you for your quick reply.

I took your sample project, I added the Buefy and imported into the main.js. If you try to do `gridsome build` you notice that the output is the same. There's no effect happening. 🤔 

Here is the updated [sample project.](https://github.com/unematiii/css-loader-short-classnames/files/5339762/gridsome-test1.zip)

Really thank you for the help!

**Comment by unematiii** [comment]
Hey!

Actually everything in Vue SFC-s do get correct class names. I guess `<style module></style>` in `*.vue` components does the trick here. (Observe the first lines of the sample projects built css file). You can enable modules for all the the other css assets by setting additionally `modules: true`:

```js
module.exports = {
  // ... other config options
  css: {
    loaderOptions: {
      css: {
        modules: true,
        localIdentName: "[local]-[hash:base64:8]",
        ...(isProduction ? { getLocalIdent: getLocalIdentName() } : {}),
      },
    },
  },
};
```

But beware, enabling modules for external libraries can cause some problems: if you yourself or the JS implementation of the library rely on static class names. Then you should use different configuration for the styles in you app and for those of external libraries.

**Comment by Tragio** [comment]
@unematiii it's now working 😄 really thank you for all the help!!!
